export const LOAD_WEB3_SUCCESS = 'LOAD_WEB3_SUCCESS';
export const LOAD_WEB3_FAIL = 'LOAD_WEB3_FAIL';
export const LOAD_BLOCKCHAIN_DATA_SUCCESS = 'LOAD_BLOCKCHAIN_DATA_SUCCESS';
export const LOAD_BLOCKCHAIN_DATA_FAIL = 'LOAD_BLOCKCHAIN_DATA_FAIL';


export const LOAD_CENT_SUCCESS = 'LOAD_CENT_SUCCESS';
export const LOAD_CENT_FAIL = 'LOAD_CENT_FAIL';
export const LOAD_CENT_BALANCE_SUCCESS = 'LOAD_CENT_BALANCE_SUCCESS';
export const LOAD_CENT_BALANCE_FAIL = 'LOAD_CENT_BALANCE_FAIL';

export const LOAD_XCENT_SUCCESS = 'LOAD_XCENT_SUCCESS';
export const LOAD_XCENT_FAIL = 'LOAD_XCENT_FAIL';
export const LOAD_XCENT_BALANCE_SUCCESS = 'LOAD_XCENT_BALANCE_SUCCESS';
export const LOAD_XCENT_BALANCE_FAIL = 'LOAD_XCENT_BALANCE_FAIL';

export const LOAD_MCENT_SUCCESS = 'LOAD_MCENT_SUCCESS';
export const LOAD_MCENT_FAIL = 'LOAD_MCENT_FAIL';
export const LOAD_MCENT_BALANCE_SUCCESS = 'LOAD_MCENT_BALANCE_SUCCESS';
export const LOAD_MCENT_BALANCE_FAIL = 'LOAD_MCENT_BALANCE_FAIL';

export const LOAD_BNB_SUCCESS = 'LOAD_BNB_SUCCESS';
export const LOAD_BNB_FAIL = 'LOAD_BNB_FAIL';
export const LOAD_BNB_BALANCE_SUCCESS = 'LOAD_BNB_BALANCE_SUCCESS';
export const LOAD_BNB_BALANCE_FAIL = 'LOAD_BNB_BALANCE_FAIL';

export const LOAD_BANK_SUCCESS = 'LOAD_BANK_SUCCESS';
export const LOAD_BANK_FAIL = 'LOAD_BANK_FAIL';
export const LOAD_BANK_BALANCE_SUCCESS = 'LOAD_BANK_BALANCE_SUCCESS';
export const LOAD_BANK_BALANCE_FAIL = 'LOAD_BANK_BALANCE_FAIL';

export const LOAD_BANK2_SUCCESS = 'LOAD_BANK2_SUCCESS';
export const LOAD_BANK2_FAIL = 'LOAD_BANK2_FAIL';
export const LOAD_BANK_BALANCE2_SUCCESS = 'LOAD_BANK_BALANCE2_SUCCESS';
export const LOAD_BANK_BALANCE2_FAIL = 'LOAD_BANK_BALANCE2_FAIL';

export const LOAD_BANK3_SUCCESS = 'LOAD_BANK3_SUCCESS';
export const LOAD_BANK3_FAIL = 'LOAD_BANK3_FAIL';
export const LOAD_BANK_BALANCE3_SUCCESS = 'LOAD_BANK_BALANCE3_SUCCESS';
export const LOAD_BANK_BALANCE3_FAIL = 'LOAD_BANK_BALANCE3_FAIL';

export const SET_LOADING_SUCCESS = 'SET_LOADING_SUCCESS';
export const SET_LOADING_FAIL = 'SET_LOADING_FAIL';


